### ISSUE TITLE
Issues found in UI and code

### ISSUE THREAD

**Issue by montoc-zz** [sanaafreen/weatherApp#1]
1. In the mobile browser, City and temperature components should be evenly divided.
Current scenario- In the mobile browser, the app looks like this- 
As you can see the city and temperature part are not evenly divided.
![screenshot_20180104-105015](https://user-images.githubusercontent.com/14260989/34551588-783ccf8c-f141-11e7-9738-2b8ef6e6f654.png)

2. The city and temperature details should only change only when the input is submitted.
Current scenario-  if you search some city, for example, New York and each time you change the text in the input box, the components shown for last submitted input are getting refreshed.

4. After input submission the page refreshment should not happen, just the component containing query details should get appended.
Current scenario- the Entire page is getting refreshed on input submission.

5. Show a warning to the user if input submitted by the user is not a correct city name.
Current scenario- No error handling just the page is getting refreshed.
![screenshot_20180104-111228](https://user-images.githubusercontent.com/14260989/34551697-3be46bd4-f142-11e7-990b-5fc1c2b69cbc.png)

6. Using Jquery inside the controller is a bad practice.

**Comment by sanaafreen** [comment]
1. Done.
2. Actually, the component is using google map API which initializes as it gets the parameter.
3. The entire page is getting refreshed because I'm adding the city names in an array and every time a new city is added all the maps and graphs are rendered.
4. Worked on this and committed the code but facing some issue, I'm sending an alert message. 
5. Will keep in mind later.
